# GNN模型训练配置文件

# 训练参数
training:
  epoch_num: 800                # 训练的总轮数
  patience: 60                  # 早停耐心值，连续多少轮无改进后停止训练
  print_interval: 30            # 打印训练信息的间隔轮数
  enable_early_stopping: true   # 是否启用早停机制

# 模型配置
model:
  type: "UserBehaviorGCN"        # 模型类型，可选 "UserBehaviorGCN" "GraphSAGE" "GCN" "GAT"
  hidden_dim: 256                # 隐藏层的维度
  output_dim: 6                  # 输出层的维度（类别数量）
  dropout: 0.3                   # Dropout比率，防止过拟合
  edge_dropout: 0.05             # 边Dropout比率，防止过拟合

# 优化器配置
optimizer:
  type: "AdamW"                  # 优化器类型
  lr: 0.003                      # 初始学习率(ReduceLROnPlateau调度器需较大初始学习率)
  weight_decay: 0.01             # 权重衰减系数，用于L2正则化

# 学习率调度器
scheduler:
  type: "ReduceLROnPlateau"             # 学习率调度器类型

  # OneCycleLR 调度器
  max_lr: 0.025                  # 最大学习率
  pct_start: 0.15                 # 学习率上升阶段占总训练的比例
  anneal_strategy: "cos"         # 学习率下降策略，"cos"或"linear"
  div_factor: 20                 # 决定 init_lr = max_lr / div_factor
  final_div_factor: 100          # 决定 min_lr = init_lr / final_div_factor

  # ReduceLROnPlateau 调度器
  mode: "min"           # 最小化验证损失
  factor: 0.6          # 学习率减少因子
  patience: 15          # 等待多少个epoch无改善后降低学习率
  min_lr: 5.0e-5        # 最小学习率
  cooldown: 5           # 冷却周期

# 类别权重计算
class_weights:
  beta: 0.9999                   # 计算类别权重的beta参数，控制平衡度
  cb_adjustment: 2.5             # 类别平衡调整系数，增大会使权重更极端

# 损失函数配置
loss:
  focal_gamma: 1.5               # Focal Loss的gamma参数，控制难例学习的强度
  label_smoothing: 0.2           # 标签平滑系数，防止过拟合
  loss_balance: 0.5              # 混合损失中各损失函数的平衡权重
  enable_r_cam: false            # 是否启用 R-CAM（强调/忽略损失）
  lp_weight: 0.2                 # 强调损失(Lp)的权重
  ln_weight: 0.2                 # 忽略损失(Ln)的权重

# 梯度处理
gradient:
  clip_norm: 2                 # 梯度裁剪阈值，防止梯度爆炸

# 强调/忽略损失特定配置
emphasis_ignore_loss:
  similarity_threshold: 0.5      # 强调/忽略损失中的相似度阈值
  max_pairs: 100                 # 每个类别最大考虑的节点对数量

# 路径配置
paths:
  model_dir: "../output/model"   # 模型保存路径
  log_dir: "../logs"             # 日志保存路径

# 评估配置
evaluation:
  visualization: true            # 是否生成可视化图表